// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace Vecinos2
{
	public partial class UserListTableCell : UITableViewCell
	{

        public static readonly NSString Key = new NSString("UserListTableCell");

        public string Name
        {
            get { return LblName.Text; }
            set { LblName.Text = value; }
        }

        public string Mail
        {
            get { return LblMail.Text; }
            set { LblMail.Text = value; }
        }

        public string Phone
        {
            get { return LblPhone.Text; }
            set { LblPhone.Text = value; }
        }

        public string Status
        {
            get { return LblStatus.Text; }
            set { LblStatus.Text = value; }

        }

        public string Address
        {
            get { return LblAddress.Text; }
            set { LblAddress.Text = value; }

        }

        public UIColor LabelColor 
        {
            set { LblStatus.TextColor = value; }
        }

        public UserListTableCell(IntPtr handle) : base(handle)
        {

        }
  
	}
}
