// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace Vecinos2
{
	public partial class AnnouncementsTableCell : UITableViewCell
	{

        public static readonly NSString Key = new NSString("AnnouncementsTableCell");

        public string AnnouncementTitle
        {
            get { return lblAnnouncementTitle.Text; }
            set { lblAnnouncementTitle.Text = value; }
        }

        public string AnnouncementDescription
        {
            get { return lblAnnouncementDescription.Text; }
            set { lblAnnouncementDescription.Text = value; }
        }

        public string AnnouncementDate
        {
            get { return lblAnnouncementDate.Text; }
            set { lblAnnouncementDate.Text = value; }
        }

        public string AnnouncementUser
        {
            get { return lblAnnouncementUser.Text; }
            set { lblAnnouncementUser.Text = value; }
        }

		public AnnouncementsTableCell (IntPtr handle) : base (handle)
		{
            
		}
	}
}
