// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace Vecinos2
{
	public partial class UserDeatailSegue : UIStoryboardSegue
	{
		public UserDeatailSegue (IntPtr handle) : base (handle)
		{
		}
	}
}
