// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace Vecinos2
{
	public partial class AreaDetailTableCell : UITableViewCell
	{
		public static readonly NSString Key = new NSString("AreaDetailTableCell");

        public string Holder
        {
            get { return LblReservationHolder.Text; }
            set { LblReservationHolder.Text = value; }
        }
		public string Date
        {
            get { return LblReservationDate.Text; }
            set { LblReservationDate.Text = value; }
        }


		public AreaDetailTableCell (IntPtr handle) : base (handle)
		{
			
		}
	}
}
