// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace Vecinos2
{
	public partial class AdminTabController : UITabBarController
	{
		public AdminTabController (IntPtr handle) : base (handle)
		{
		}


	}
}
