// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace tablas10
{
	public partial class TwitTableCell : UITableViewCell
	{
        //This code was not autogenerated
        #region properties

        public UIImage ProfileImage
        {
            

            get => imgUserProfileImage.Image;
            set => imgUserProfileImage.Image = value;
        }

        public string TweetText
        {
            get => lblTweetText.Text;
            set => lblTweetText.Text = value;
        }

        public string UserName
        {
            get => lblUserScreenName.Text;
            set => lblUserScreenName.Text = value;
        }

        #endregion



		public TwitTableCell (IntPtr handle) : base (handle)
		{
            
		}
	}
}
